export {
  formatINR,
  formatINRCompact,
  formatDateIST,
  formatDateShortIST,
  formatTimeIST,
  formatIndiaPhone,
  isValidIndiaPhone,
  isValidIndiaPincode,
  normalizeIndiaPhone,
  indiaPhoneSchema,
  indiaPincodeSchema,
  INDIA_PHONE_REGEX,
  INDIA_PINCODE_REGEX,
} from "@storm/contracts/format";
