apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - otel-collector.yaml
  - prometheus-rules.yaml

configMapGenerator:
  - name: storm-grafana-dashboards
    files:
      - grafana-dashboards/service-health.json
      - grafana-dashboards/business-kpis.json
      - grafana-dashboards/resource-health.json
      - grafana-dashboards/saga-health.json
    options:
      labels:
        grafana_dashboard: "1"
