/**
 * Storm error code catalog.
 *
 * Format: SCOPE_REASON (upper-snake). Codes are stable once shipped;
 * frontends switch on them. Add new codes here as services come online.
 */
export const ErrorCodes = {
  // Generic — usable across services
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  IDEMPOTENCY_KEY_REUSE: "IDEMPOTENCY_KEY_REUSE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // identity-service
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_BLOCKED: "ACCOUNT_BLOCKED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
  WEAK_PASSWORD: "WEAK_PASSWORD",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  REFRESH_REUSE_DETECTED: "REFRESH_REUSE_DETECTED",
  CSRF_INVALID: "CSRF_INVALID",
  OTP_INVALID: "OTP_INVALID",
  OTP_EXHAUSTED: "OTP_EXHAUSTED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
