/**
 * Storm error code catalog.
 *
 * Format: SCOPE_REASON (upper-snake). Codes are stable once shipped;
 * frontends switch on them. Add new codes here as services come online.
 */
export const ErrorCodes = {
  // Generic — usable across services
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  IDEMPOTENCY_KEY_REUSE: "IDEMPOTENCY_KEY_REUSE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // identity-service
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_BLOCKED: "ACCOUNT_BLOCKED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  WEAK_PASSWORD: "WEAK_PASSWORD",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  REFRESH_REUSE_DETECTED: "REFRESH_REUSE_DETECTED",
  CSRF_INVALID: "CSRF_INVALID",
  OTP_INVALID: "OTP_INVALID",
  OTP_EXHAUSTED: "OTP_EXHAUSTED",
  ADDRESS_LIMIT_REACHED: "ADDRESS_LIMIT_REACHED",
  ADDRESS_DEFAULT_REQUIRED: "ADDRESS_DEFAULT_REQUIRED",

  // catalog-service
  SKU_TAKEN: "SKU_TAKEN",
  SLUG_TAKEN: "SLUG_TAKEN",
  CATEGORY_DEPTH_EXCEEDED: "CATEGORY_DEPTH_EXCEEDED",
  CATEGORY_HAS_CHILDREN: "CATEGORY_HAS_CHILDREN",
  CATEGORY_HAS_PRODUCTS: "CATEGORY_HAS_PRODUCTS",
  BRAND_HAS_PRODUCTS: "BRAND_HAS_PRODUCTS",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  PUBLISH_REQUIREMENTS_NOT_MET: "PUBLISH_REQUIREMENTS_NOT_MET",
  PRODUCT_NOT_PUBLISHED: "PRODUCT_NOT_PUBLISHED",

  // media-service
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  MEDIA_NOT_READY: "MEDIA_NOT_READY",
  UPLOAD_EXPIRED: "UPLOAD_EXPIRED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
