apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.4
    helm:
      values: |
        installCRDs: true
        webhook:
          podAnnotations:
            linkerd.io/inject: enabled
        certController:
          podAnnotations:
            linkerd.io/inject: enabled
        serviceAccount:
          create: true
          name: external-secrets
          annotations:
            # Filled in via Terraform output `irsa_role_arns.external_secrets`.
            eks.amazonaws.com/role-arn: ""
  destination:
    name: in-cluster
    namespace: external-secrets
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true", "ServerSideApply=true"]
